metadata.format.version = "1.1"

[versions]

# Libraries
gson = "2.10.1"
guava = "32.1.2-jre"
caffeine = "3.1.5"
annotations = "24.1.0"

adventure = "4.15.0"
adventure-platform = "4.3.2"

brigadier = "1.0.18"
authlib = "1.5.26" # 3.11.50
types = "1.1"
settings = "1.0"
delivery4j = "1.0"

# Platforms
bukkit = "1.20.6-R0.1-SNAPSHOT"
bungeecord = "1.20-R0.2-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"

# Plugins
shadow = "8.1.1"

[libraries]

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-platform-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platform" }

brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
types = { module = "com.saicone:types", version.ref = "types" }
settings = { module = "com.saicone.settings:settings", version.ref = "settings" }
delivery4j = { module = "com.saicone.delivery4j:delivery4j", version.ref = "delivery4j" }

bukkit-api = { module = "org.spigotmc:spigot-api", version.ref = "bukkit" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

[plugins]

shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }