import org.gradle.api.attributes.java.TargetJvmVersion

repositories {
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
}

configurations.all {
    if (canBeResolved) {
        attributes {
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 25)
        }
    }
}

dependencies {
    compileOnly libs.paper.api
    compileOnlyApi project(':platform:platform-paper')
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}