import org.gradle.api.attributes.java.TargetJvmVersion

repositories {
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
    maven { url = uri('https://repo.codemc.io/repository/nms/') }
}

configurations.all {
    if (canBeResolved) {
        attributes {
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 25)
        }
    }
}

dependencies {
    compileOnly libs.paper.api
    compileOnly(libs.spigot) {
        transitive = false
    }
    api project(':platform:platform-bukkit')
    compileOnlyApi libs.nbt.mapper.minecraft

    // Task module
    compileOnly project(':module:module-task')

    // Env module
    compileOnly project(':module:module-env')
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}